AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  ParameterName:
    Type: String
    Description: The name of the SSM Parameter Store parameter holding Spotify credentials
    Default: /spotify/credentials

Resources:
  SpotifyUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handlers.spotify_handler.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          PARAMETER_NAME: !Ref ParameterName
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 1/2 * ? *)
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: ssm:GetParameter
              Resource: !Sub |
                arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterName}