AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  SecretName:
    Type: String
    Description: The name of the secret in AWS Secrets Manager
    Default: spotify/credentials

Resources:
  SpotifyUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handlers.spotify_handler.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 1/2 * ? *)
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub |
                arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*